### PR TITLE
Object oriented adaptation

### PR DESCRIPTION
**Pull request by xZero707**
For simplicity sake and more technical beauty for usage, whole code was adapted to class version.
There are also more changes in the code for easier reading and modifications of some parts.

### CODE REVIEW

**Comment by Falicon** [comment]
Nice. I like the class version, but don't want to update the core project with it for backwards comp. stuff...it seems like it's a big enough/useful enough change though that you might want to fork the project and maint. that version  under your account?

**Comment by xZero707** [comment]
Yeah sure, that's understandable and I expected that answer. I don't understand last part of your response: "it seems like it's a big enough/useful enough change though that you might want to fork the project and maint. that version under your account?"

**Comment by Falicon** [comment]
I just mean that you can/should make that version available via a repo
under your github account...then people that want a class based version can
use your more updated/modern version.

On Wed, Mar 4, 2015 at 9:43 PM, Aleksandar Puharic <notifications@github.com

**Comment by xZero707** [comment]
Ok, understood, and I'm glad that I have your allowance to do that.

**Pull request closed without merging**
